### ISSUE TITLE
tile.openstreetmap.jp の更新作業をペアプロ的に観察させてほしい

### ISSUE THREAD

**Issue by yuiseki** [UNopenGIS/77#1]
日本語で失礼します。

## What

- tile.openstreetmap.jp は、OpenStreetMap Foundation Japanによって提供されている、地球惑星規模のタイルサーバーです
- tile.openstreetmap.jp の運用は、DWG7 Objective 7のObjective Ownerである @smellman が担当しており、毎週更新作業を行っているとのことです
- この更新作業を、時間を合わせて、画面共有などで、ペアプロ的に観察させていただきたいと思っています

## Why

- tile.openstreetmap.jp は、世界でも数少ない、定期的に更新されている惑星規模のタイルサーバーです
- tile.openstreetmap.jp は、全てがOSSで構成されているとのことです
- このタイルサーバーを更新している様子を観察させていただくことで、惑星規模のタイルサーバーを構築・更新するための具体的な知見を理解し、再現し、文書化し、共有することが目的です

## How

- @smellman が同意してくれれば、日程を調整させていただきたいです
- Google MeetまたはZoomで画面を共有して、説明していただきながら作業を進めてもらいたいです

## Screenshots

[![Image from Gyazo](https://i.gyazo.com/befc7243ee37d559293bf7a32612010c.png)](https://gyazo.com/befc7243ee37d559293bf7a32612010c)

**Comment by hfu** [comment]
面白そうですね！もしもこれが実現する場合は、私も参加させてもらえると嬉しいです。

同期的な同席ではなくても、例えば [asciinema](https://asciinema.org/) でシェアしてもらえたのを非同期に鑑賞するだけでも勉強になりそうだと感じました。

**Comment by smellman** [comment]
Planetのaws s3 mirrorが出てきたのを目視したら作業開始なので、時間の調整は難しい点はご了承いただきたい。
aws s3 mirrorは良いときは日曜日の昼ぐらいに出ていますが、日曜日の夜になるケースもあります。(最悪夜中になります)。また、全日土曜日に出てくるという日もあります。
あと、コマンドを一つ叩いたら4時間ほどなにもすることがありません。ただレンタリングを待つという時間になります。
あと、tmux前提の作業なのでasciinemaでちゃんと録画できるか心配ではあります。
正直、時間の調整が大変なので、調整をせずにどこかで「これからやります」とアナウンスする感じになるかと思います。

**Comment by yuiseki** [comment]
2022-12-11 に tile.openstreetmap.jp の更新を観察させていただけたので、このIssueは閉じます。
ありがとうございました！

tile.openstreetmap.jp の更新 2022-12-11 https://scrapbox.io/yuiseki/tile.openstreetmap.jp_%E3%81%AE%E6%9B%B4%E6%96%B0_2022-12-11
